"""Curated seed catalog for Home Assistant.

Read tools auto-run (with response projection); `call_service` is mutating and
routes through the operator approval queue. Seeded idempotently via the
Integrations UI's "Seed" action.
"""

HA_SEED_TOOLS = [
    {
        "name": "list_entities",
        "description": "List all Home Assistant entities and their current state (entity_id, state, friendly name). Use search to filter by entity_id substring, and limit to bound the result. Use this to discover entity ids.",
        "method": "GET",
        "path_template": "/states",
        "params": [],
        "fields": ["entity_id", "state", "attributes.friendly_name"],
        "search_field": "entity_id",
        "example": '[{"entity_id": "light.living_room", "state": "on", "friendly_name": "Living Room"}]',
        "read_only": True,
    },
    {
        "name": "get_entity",
        "description": "Get a single entity's full state and attributes (e.g. light.living_room).",
        "method": "GET",
        "path_template": "/states/{entity_id}",
        "params": [
            {"name": "entity_id", "type": "string", "description": "Entity id (e.g. light.living_room).", "required": True},
        ],
        "fields": ["entity_id", "state", "attributes"],
        "example": '{"entity_id": "light.living_room", "state": "on", "attributes": {"friendly_name": "Living Room"}}',
        "read_only": True,
    },
    {
        "name": "call_service",
        "description": "Call a Home Assistant service (e.g. light.turn_on, light.turn_off, climate.set_temperature, switch.toggle). Pass service data as a JSON object. REQUIRES OPERATOR APPROVAL.",
        "method": "POST",
        "path_template": "/services/{domain}/{service}",
        "params": [
            {"name": "domain", "type": "string", "description": "Service domain (e.g. light, climate, switch).", "required": True},
            {"name": "service", "type": "string", "description": "Service name (e.g. turn_on, set_temperature).", "required": True},
            {"name": "data", "type": "json", "description": "Service data as a JSON object, e.g. {\"entity_id\": \"light.living_room\", \"brightness\": 128}.", "required": False},
        ],
        "example": '[]',
        "read_only": False,
    },
    {
        "name": "list_services",
        "description": "List every Home Assistant service with its field schema (names, types, required/optional) — learn the exact fields a service accepts before calling it. Returns the full schema map.",
        "method": "GET",
        "path_template": "/services",
        "params": [],
        "fields": [],
        "example": '{"light": {"turn_on": {"name": "Turn On", "fields": {"entity_id": {"selector": {"entity": {}}}}}}}',
        "read_only": True,
    },
    {
        "name": "get_config",
        "description": "Get the Home Assistant core configuration (location, units, timezone, version).",
        "method": "GET",
        "path_template": "/config",
        "params": [],
        "fields": ["location_name", "latitude", "longitude", "elevation", "unit_system", "time_zone", "version"],
        "example": '{"location_name": "Home", "latitude": 51.5, "longitude": -0.12, "elevation": 20, "unit_system": {"length": "km"}, "time_zone": "Europe/London", "version": "2026.7.3"}',
        "read_only": True,
    },
    {
        "name": "get_history",
        "description": "Get the recorded state history for an entity (or all) from a start time (ISO8601). filter_entity_id narrows to one entity; end_time bounds the window. Returns the raw history (list of per-entity state lists).",
        "method": "GET",
        "path_template": "/history/period/{start}",
        "params": [
            {"name": "start", "type": "string", "description": "Start time, ISO8601 (e.g. 2026-08-18T00:00:00).", "required": True},
            {"name": "filter_entity_id", "type": "string", "description": "Restrict to one entity (e.g. sensor.outside_temp).", "required": False},
            {"name": "end_time", "type": "string", "description": "End time, ISO8601 (optional).", "required": False},
        ],
        "fields": [],
        "example": '[[{"entity_id": "sensor.x", "state": "20", "last_changed": "2026-08-18T00:00:00"}]]',
        "read_only": True,
    },
    {
        "name": "list_entity_registry",
        "description": "List the Home Assistant entity registry — ALL registered entities, including disabled/hidden ones /api/states never shows. Use device_id to get every entity of one device, search to filter by entity_id substring, limit to bound. disabled_by (null/'integration'/'user') distinguishes a disabled entity from one never created.",
        "method": "GET",
        "path_template": "config/entity_registry/list",
        "params": [],
        "fields": ["entity_id", "name", "platform", "disabled_by", "device_id", "config_entry_id", "area_id"],
        "search_field": "entity_id",
        "filter_fields": ["device_id"],
        "transport": "ws",
        "example": '[{"entity_id": "sensor.smoke_rssi", "name": "Smoke RSSI", "platform": "mqtt", "disabled_by": "integration", "device_id": "dev123", "config_entry_id": "ce1", "area_id": "a1"}]',
        "read_only": True,
    },
    {
        "name": "list_device_registry",
        "description": "List the Home Assistant device registry — every device with manufacturer, model, identifiers, connections, and via_device_id (what it joins through). Use search to filter by device name substring, limit to bound.",
        "method": "GET",
        "path_template": "config/device_registry/list",
        "params": [],
        "fields": ["id", "name", "name_by_user", "manufacturer", "model", "identifiers", "connections", "via_device_id", "entry_type", "area_id"],
        "search_field": "name",
        "transport": "ws",
        "example": '[{"id": "dev123", "name": "Smoke Detector", "manufacturer": "Tuya", "model": "_TZE284_gyzlwu5q TS0601", "identifiers": [["zigbee", "a4:c1:38:53:2b:6a:d6:5f"]], "via_device_id": "dev-coord"}]',
        "read_only": True,
    },
    {
        "name": "lovelace_dashboards",
        "description": "List the Home Assistant Lovelace dashboards as a compact inventory: dashboard_id, url_path, title, icon, mode, show_in_sidebar, require_admin (filename for YAML-mode dashboards). Use this to discover url_path (for config reads/writes) and dashboard_id (for update/delete). Pass full=true for the raw rows.",
        "method": "GET",
        "path_template": "",
        "transport": "ws",
        "handler": "ha_lovelace_dashboards",
        "params": [
            {"name": "full", "type": "boolean", "description": "Return the raw dashboard rows instead of the compact inventory.", "required": False, "default": False},
        ],
        "fields": [],
        "example": '[{"dashboard_id": "water_monitor", "url_path": "water-monitor", "title": "Water", "icon": "mdi:water", "mode": "storage", "show_in_sidebar": true, "require_admin": false}]',
        "read_only": True,
    },
    {
        "name": "lovelace_dashboard",
        "description": "Read ONE Lovelace dashboard config, summarised by default (top_level_keys + per-view card list with best-effort entity/statistic targets) so a large dashboard never floods context. Identify the dashboard by url_path; pass full=true for the verbatim config (with size_bytes/truncated), or view=<index|path|title> to narrow to one view. Cards may reference external statistic ids like 'thames_water:thameswater_consumption' — these are collected, never validated.",
        "method": "GET",
        "path_template": "",
        "transport": "ws",
        "handler": "ha_lovelace_dashboard",
        "params": [
            {"name": "url_path", "type": "string", "description": "Dashboard url_path (from lovelace_dashboards). Omit for the default dashboard (only if one has a saved config).", "required": False},
            {"name": "view", "type": "string", "description": "Keep only this view: 0-based index, or the view's path/title.", "required": False},
            {"name": "full", "type": "boolean", "description": "Return the verbatim config instead of the summary.", "required": False, "default": False},
            {"name": "max_bytes", "type": "integer", "description": "full only: refuse (truncated=true) when the config exceeds this many bytes.", "required": False, "default": 20000},
        ],
        "fields": [],
        "example": '{"url_path": "water-monitor", "dashboard_id": "water_monitor", "mode": "storage", "view_count": 1, "config_hash": "sha256-hex", "top_level_keys": ["title", "views"], "views": [{"index": 0, "path": "water", "title": "Consumption", "card_count": 5, "cards": [{"index": 0, "type": "statistics-graph", "targets": ["thames_water:thameswater_consumption"]}]}]}',
        "read_only": True,
    },
    {
        "name": "lovelace_create_dashboard",
        "description": "Create a storage-mode Lovelace dashboard. url_path must contain a hyphen (-) unless allow_single_word is true. Pre-flights the existing dashboards and returns ha_dashboard_url_exists with the existing dashboard_id instead of failing upstream; returns the created item (incl. dashboard_id) and verifies it appears in the list.",
        "method": "POST",
        "path_template": "",
        "transport": "ws",
        "handler": "ha_lovelace_create_dashboard",
        "params": [
            {"name": "title", "type": "string", "description": "Dashboard title (shown in the sidebar).", "required": True},
            {"name": "url_path", "type": "string", "description": "URL path (e.g. water-monitor). Must contain a hyphen unless allow_single_word.", "required": True},
            {"name": "icon", "type": "string", "description": "Optional icon (e.g. mdi:water).", "required": False},
            {"name": "show_in_sidebar", "type": "boolean", "description": "Show the dashboard in the sidebar (default true).", "required": False, "default": True},
            {"name": "require_admin", "type": "boolean", "description": "Restrict the dashboard to admins (default false).", "required": False, "default": False},
            {"name": "allow_single_word", "type": "boolean", "description": "Allow a url_path with no hyphen (escape hatch; default false).", "required": False, "default": False},
        ],
        "fields": [],
        "example": '{"dashboard_id": "water_monitor", "url_path": "water-monitor", "title": "Water", "icon": "mdi:water", "mode": "storage", "show_in_sidebar": true, "require_admin": false, "verified": true}',
        "read_only": False,
    },
    {
        "name": "lovelace_update_dashboard",
        "description": "Update a Lovelace dashboard's metadata (title, icon, show_in_sidebar, require_admin). Identify it by dashboard_id OR url_path (the url_path -> dashboard_id mapping is resolved server-side). YAML-mode dashboards are refused. Returns the updated item.",
        "method": "POST",
        "path_template": "",
        "transport": "ws",
        "handler": "ha_lovelace_update_dashboard",
        "params": [
            {"name": "dashboard_id", "type": "string", "description": "Dashboard id (from lovelace_dashboards).", "required": False},
            {"name": "url_path", "type": "string", "description": "Dashboard url_path (alt to dashboard_id).", "required": False},
            {"name": "title", "type": "string", "description": "New title.", "required": False},
            {"name": "icon", "type": "string", "description": "New icon (e.g. mdi:water).", "required": False},
            {"name": "show_in_sidebar", "type": "boolean", "description": "Show/hide in the sidebar.", "required": False},
            {"name": "require_admin", "type": "boolean", "description": "Restrict to admins.", "required": False},
        ],
        "fields": [],
        "example": '{"dashboard_id": "water_monitor", "url_path": "water-monitor", "title": "Water usage", "mode": "storage"}',
        "read_only": False,
    },
    {
        "name": "lovelace_save_config",
        "description": "Safely edit a Lovelace dashboard config. Preferred: ops=[{op:'append_card'|'set_card'|'delete_card', view:<index|path|title>, card_index?, card?}, {op:'set_view'|'delete_view', view:<index|path|title|'new'>, view_config?}] — the tool reads, patches, diffs, writes, then RE-READS to verify (a blind lovelace/config/save replaces the whole dashboard). dry_run=true returns the diff without writing. Full replace is possible with config + confirm='replace'. Pass expect_hash (from a prior read) to refuse a write if the live config changed. Unknown top-level keys (e.g. kiosk_mode) are preserved. YAML-mode dashboards are refused. REQUIRES OPERATOR APPROVAL unless dry_run.",
        "method": "POST",
        "path_template": "",
        "transport": "ws",
        "handler": "ha_lovelace_save_config",
        "always_gate": True,
        "params": [
            {"name": "url_path", "type": "string", "description": "Dashboard url_path. Omit for the default dashboard.", "required": False},
            {"name": "ops", "type": "array", "description": "Patch operations (preferred). See the tool description for the op shapes.", "required": False},
            {"name": "config", "type": "json", "description": "Full replacement config (object or JSON string); requires confirm='replace'.", "required": False},
            {"name": "confirm", "type": "string", "description": "Must be the literal 'replace' when using config.", "required": False},
            {"name": "expect_hash", "type": "string", "description": "sha256 of the config you read (the `config_hash` returned by lovelace_dashboard); write is refused if the live config no longer matches.", "required": False},
            {"name": "dry_run", "type": "boolean", "description": "Return the diff without writing (runs without approval).", "required": False, "default": False},
        ],
        "fields": [],
        "example": '{"changed": true, "url_path": "water-monitor", "diff": {"views_added": 0, "views_removed": 0, "cards_added": 1, "cards_removed": 0, "cards_changed": 0}, "verified": true}',
        "read_only": False,
    },
    {
        "name": "lovelace_delete_dashboard",
        "description": "Delete a storage-mode Lovelace dashboard by dashboard_id OR url_path. Deleting a storage dashboard also removes its stored config (HA cleans it up), so no orphan is left. YAML-mode dashboards are refused (they are file-backed). Verifies the dashboard is gone and reports dashboard_id/url_path. REQUIRES OPERATOR APPROVAL.",
        "method": "POST",
        "path_template": "",
        "transport": "ws",
        "handler": "ha_lovelace_delete_dashboard",
        "always_gate": True,
        "params": [
            {"name": "dashboard_id", "type": "string", "description": "Dashboard id (from lovelace_dashboards).", "required": False},
            {"name": "url_path", "type": "string", "description": "Dashboard url_path (alt to dashboard_id).", "required": False},
        ],
        "fields": [],
        "example": '{"deleted": true, "dashboard_id": "water_monitor", "url_path": "water-monitor", "verified": true}',
        "read_only": False,
    },
]


def seed_ha_tools(integration_id: int):
    """Idempotently insert/refresh the curated Home Assistant seed tools for an
    integration. Existing tools with the same name are updated in place; new
    ones are created. Returns (created, updated) counts."""
    from db.integrations import create_tool, get_tools, update_tool

    existing = {t['name']: t for t in get_tools(integration_id)}
    created = 0
    updated = 0
    for tool in HA_SEED_TOOLS:
        if tool['name'] in existing:
            update_tool(
                existing[tool['name']]['id'],
                name=tool['name'],
                description=tool['description'],
                method=tool['method'],
                path_template=tool['path_template'],
                params=tool['params'],
                fields=tool.get('fields'),
                search_field=tool.get('search_field'),
                filter_fields=tool.get('filter_fields'),
                transport=tool.get('transport', 'http'),
                version=tool.get('version', 'v1'),
                strip_envelope=tool.get('strip_envelope'),
                transform=tool.get('transform'),
                handler=tool.get('handler'),
                always_gate=bool(tool.get('always_gate')),
                error_codes=tool.get('error_codes'),
                path_variants=tool.get('path_variants'),
                response_hint=tool.get('response_hint'),
                example=tool['example'],
                read_only=tool['read_only'],
                seeded=True,
            )
            updated += 1
        else:
            create_tool(
                integration_id,
                tool['name'],
                tool['description'],
                tool['method'],
                tool['path_template'],
                tool['params'],
                tool['example'],
                read_only=tool['read_only'],
                fields=tool.get('fields'),
                search_field=tool.get('search_field') or '',
                filter_fields=tool.get('filter_fields'),
                transport=tool.get('transport', 'http'),
                version=tool.get('version', 'v1'),
                strip_envelope=tool.get('strip_envelope'),
                transform=tool.get('transform') or '',
                handler=tool.get('handler') or '',
                always_gate=bool(tool.get('always_gate')),
                error_codes=tool.get('error_codes'),
                path_variants=tool.get('path_variants'),
                response_hint=tool.get('response_hint'),
                seeded=True,
            )
            created += 1
    return created, updated
