"""Unified MCP tool execution + gating.

Every tool function generated by `core.mcp_server._build_tool_fn` delegates here.
`run_tool` loads the integration + tool, applies the integration's `gate_mode`
policy (all / destructive / none), executes the call (curated HTTP, generic HTTP,
or WebSocket), shapes read responses client-side, and returns the JSON string to
hand back to the model. This keeps all the runtime logic in one tested place
instead of in generated code strings.
"""
import json

from db.integrations import (
    create_pending_call,
    get_integration,
    get_tool,
)
from core.integration_proxy import (
    ProxyError,
    _apply_shaping,
    execute_generic_call,
    execute_integration_call,
    is_destructive,
    merge_response_hint,
)
from core.ha_ws import execute_ws_call

AGENT_LABEL = 'mcp'


def _error(msg, status_code=500):
    return json.dumps({'error': msg, 'status_code': status_code})


def run_tool(integration_name: str, tool_name: str, args: dict, reason: str = '') -> str:
    """Execute (or gate) one MCP tool call and return the JSON string for the model."""
    integration = get_integration(integration_name)
    if not integration or not integration.get('enabled'):
        return _error("Integration not found or disabled", 404)
    tool = get_tool(integration_name, tool_name)
    if not tool or not tool.get('enabled'):
        return _error("Tool not found or disabled", 404)

    args = args or {}
    # Phase 2: MCP tool calls accept structured session_id / execution_id so the
    # dashboard groups them with SSH commands from the same agent conversation.
    # Popped here so they never reach the upstream API as forwarded params.
    session_id = (args.pop('session_id', '') or '')[:64]
    execution_id = (args.pop('execution_id', '') or '')[:64]
    if tool.get('not_implemented'):
        return json.dumps({'error': 'not_implemented',
                           'message': f"{tool_name} is declared in the catalog "
                                      "but not implemented yet",
                           'status_code': 501})
    transport = tool.get('transport') or 'http'
    generic = bool(tool.get('generic'))
    mutating = not tool.get('read_only')
    handler = tool.get('handler') or ''
    # Audit labels: an immediate mutating call ran without operator sign-off
    # ("auto"); reads and handler dry-runs are not approval-relevant.
    approval_label = 'auto' if (mutating and not args.get('dry_run')) else ''
    exec_reason = reason if mutating else ''

    def _execute():
        if handler:
            # Curated multi-step handler — returns the final JSON string itself.
            from core.tool_handlers import run_handler
            return run_handler(handler, integration, tool, args,
                               agent=AGENT_LABEL, session_id=session_id,
                               execution_id=execution_id,
                               reason=exec_reason, approval=approval_label)
        if transport == 'ws':
            # WS tools (curated registry tools or generic ws tools) run the
            # command from path_template / the command arg.
            command = tool.get('path_template') or args.get('command') or ''
            payload = args.get('payload')
            return execute_ws_call(integration, command, payload,
                                   agent=AGENT_LABEL, tool_name=tool_name,
                                   session_id=session_id, execution_id=execution_id,
                                   reason=exec_reason, approval=approval_label)
        if generic:
            return execute_generic_call(
                integration, args.get('method'), args.get('path'),
                args.get('params'), args.get('data'),
                agent=AGENT_LABEL, tool_name=tool_name, root=bool(args.get('root')),
                session_id=session_id, execution_id=execution_id,
                reason=exec_reason, approval=approval_label)
        return execute_integration_call(integration, tool, args, agent=AGENT_LABEL,
                                        session_id=session_id, execution_id=execution_id,
                                        reason=exec_reason, approval=approval_label)

    # Read-only: always execute (auto-run + audit) and shape client-side.
    if not mutating:
        try:
            res = _execute()
        except ProxyError as e:
            return _error(e.message, e.status_code)
        if handler:
            return res
        if res.get('error'):
            return json.dumps({'error': res['error'], 'status_code': res.get('status_code')})
        if tool.get('transform') and transport != 'ws':
            # execute_integration_call already ran the registered transform —
            # shaping it again would double-apply (e.g. charts downsample).
            # WS tools do NOT run transforms in execute_ws_call, so they fall
            # through to _apply_shaping below.
            return res['body']
        return _apply_shaping(res['body'], tool, args, integration)

    # Mutating: consult the integration's gating policy.
    if generic and not handler:
        method = args.get('method') or 'POST'
        path = args.get('path') or args.get('command') or ''
    else:
        method = tool.get('method') or 'GET'
        path = tool.get('path_template') or ''
    destructive = is_destructive(method, path)
    gate_mode = (integration.get('gate_mode') or 'destructive').lower()
    should_gate = (gate_mode == 'all'
                   or (gate_mode == 'destructive' and destructive)
                   or bool(tool.get('always_gate')))
    # A handler dry-run never writes upstream, so it runs pre-gate regardless
    # of the tool's gating policy.
    if handler and args.get('dry_run'):
        should_gate = False

    if should_gate:
        if handler:
            # Validate the write (read → patch → diff, no write) before queuing
            # an approval, so an operator never spends an approval on a write
            # that cannot succeed.
            from core.tool_handlers import run_preflight
            pre = run_preflight(handler, integration, tool, args,
                                agent=AGENT_LABEL, session_id=session_id,
                                execution_id=execution_id)
            if pre is not None:
                return pre
        call_id = create_pending_call(integration['name'], tool_name, args, reason,
                                      session_id=session_id, execution_id=execution_id)
        from core.notify import send_notify
        send_notify('jit', 'API Approval Required',
                    '`%s` on %s: ' % (tool_name, integration_name) + (reason or '')[:80])
        return json.dumps({'status': 'pending', 'id': call_id,
                           'message': 'Awaiting operator approval. Call check_approval(%d) to poll.' % call_id})

    try:
        res = _execute()
    except ProxyError as e:
        return _error(e.message, e.status_code)
    if handler:
        return res
    if res.get('error'):
        return json.dumps({'error': res['error'], 'status_code': res.get('status_code')})
    return merge_response_hint(tool, res['body'])
