"""Unified MCP tool execution + gating.

Every tool function generated by `core.mcp_server._build_tool_fn` delegates here.
`run_tool` loads the integration + tool, applies the integration's `gate_mode`
policy (all / destructive / none), executes the call (curated HTTP, generic HTTP,
or WebSocket), shapes read responses client-side, and returns the JSON string to
hand back to the model. This keeps all the runtime logic in one tested place
instead of in generated code strings.
"""
import json

from db.integrations import (
    create_pending_call,
    get_integration,
    get_tool,
)
from core.integration_proxy import (
    ProxyError,
    _apply_shaping,
    execute_generic_call,
    execute_integration_call,
    is_destructive,
    merge_response_hint,
)
from core.ha_ws import execute_ws_call

AGENT_LABEL = 'mcp'


def _error(msg, status_code=500):
    return json.dumps({'error': msg, 'status_code': status_code})


def run_tool(integration_name: str, tool_name: str, args: dict, reason: str = '') -> str:
    """Execute (or gate) one MCP tool call and return the JSON string for the model."""
    integration = get_integration(integration_name)
    if not integration or not integration.get('enabled'):
        return _error("Integration not found or disabled", 404)
    tool = get_tool(integration_name, tool_name)
    if not tool or not tool.get('enabled'):
        return _error("Tool not found or disabled", 404)

    args = args or {}
    if tool.get('not_implemented'):
        return json.dumps({'error': 'not_implemented',
                           'message': f"{tool_name} is declared in the catalog "
                                      "but not implemented yet",
                           'status_code': 501})
    transport = tool.get('transport') or 'http'
    generic = bool(tool.get('generic'))
    mutating = not tool.get('read_only')

    def _execute():
        if transport == 'ws':
            # WS tools (curated registry tools or generic ws tools) run the
            # command from path_template / the command arg.
            command = tool.get('path_template') or args.get('command') or ''
            payload = args.get('payload')
            return execute_ws_call(integration, command, payload,
                                   agent=AGENT_LABEL, tool_name=tool_name)
        if generic:
            return execute_generic_call(
                integration, args.get('method'), args.get('path'),
                args.get('params'), args.get('data'),
                agent=AGENT_LABEL, tool_name=tool_name)
        return execute_integration_call(integration, tool, args, agent=AGENT_LABEL)

    # Read-only: always execute (auto-run + audit) and shape client-side.
    if not mutating:
        try:
            res = _execute()
        except ProxyError as e:
            return _error(e.message, e.status_code)
        if res.get('error'):
            return json.dumps({'error': res['error'], 'status_code': res.get('status_code')})
        if tool.get('transform'):
            # execute_integration_call already ran the registered transform —
            # shaping it again would double-apply (e.g. charts downsample).
            return res['body']
        return _apply_shaping(res['body'], tool, args)

    # Mutating: consult the integration's gating policy.
    if generic:
        method = args.get('method') or 'POST'
        path = args.get('path') or args.get('command') or ''
    else:
        method = tool.get('method') or 'GET'
        path = tool.get('path_template') or ''
    destructive = is_destructive(method, path)
    gate_mode = (integration.get('gate_mode') or 'destructive').lower()
    should_gate = (gate_mode == 'all'
                   or (gate_mode == 'destructive' and destructive)
                   or bool(tool.get('always_gate')))

    if should_gate:
        call_id = create_pending_call(integration['name'], tool_name, args, reason)
        from core.notify import send_notify
        send_notify('jit', 'API Approval Required',
                    '`%s` on %s: ' % (tool_name, integration_name) + (reason or '')[:80])
        return json.dumps({'status': 'pending', 'id': call_id,
                           'message': 'Awaiting operator approval. Call check_approval(%d) to poll.' % call_id})

    try:
        res = _execute()
    except ProxyError as e:
        return _error(e.message, e.status_code)
    if res.get('error'):
        return json.dumps({'error': res['error'], 'status_code': res.get('status_code')})
    return merge_response_hint(tool, res['body'])
